project:
  type: website
  output-dir: docs
  
website:
  title: "Random Projections"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sodavann
      - icon: linkedin
        href: https://www.linkedin.com/leo-andersson
format:
  html:
    theme: lux
    css: styles.css


